### ISSUE TITLE
Run spatial_stream_cnn.py valueError

### ISSUE THREAD

**Issue by OliviaMG** [wadhwasahil/Video-Classification-2-Stream-CNN#8]
Hi @wadhwasahil
Thanks guys share your code, when i run your code i got a valueError:
Using TensorFlow backend.
Making model...
Compiling model...
Loading train dictionary...
Loading test dictionary...
Training model...
spatial_stream_cnn.py:27: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (X_train != None and Y_train != None):
Traceback (most recent call last):
  File "spatial_stream_cnn.py", line 178, in <module>
    batch_size)
  File "spatial_stream_cnn.py", line 75, in train
    datagen.fit(X_sample)
  File "/Users/WarmingBug/anaconda/lib/python2.7/site-packages/keras/preprocessing/image.py", line 578, in fit
    'Got array with shape: ' + str(x.shape))
ValueError: Input to `.fit()` should have rank 4. Got array with shape: (0,)
would you mind tell me how to fix this problem. Thanks alot.

**Comment by wadhwasahil** [comment]
We have used theano as backend. But since you are using tensorflow as the backend (which is awesome), the error which you are facing is due to dimension mismatch. Convolution in tensorflow requires a 4 dimension array [batch_size, X, Y, no_channels]. But in your case, the input is probably is a **list()** having dimension (0,). 
It could possibly mean that your batch size is 0, so **IMHO** try to convert your input into a 4 dim array.
For more reading, https://www.tensorflow.org/api_docs/python/tf/nn/conv2d

**Comment by wadhwasahil** [comment]
@OliviaMG shall I close the issue for now?

**Comment by OliviaMG** [comment]
@wadhwasahil Thank you very much. Yes, the problem i fixed and you can close it now. :)
